/*
  Source code is in UTF-8 encoding. The following symbols may appear, among others:
  α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω « • ¦ » ∀ ∃ ∷ … → ← ﬁ ﬂ ƒ
  If you can't read this, you're out of luck. This code was generated with the frege compiler version 3.24.100
  from src/main/frege/io/github/mchav/FregeCode.fr Do not edit this file! Instead, edit the source file and recompile.
*/

package io.github.mchav.fregeandroid;

import frege.run7.Func;
import frege.run7.Lazy;
import frege.run7.Thunk;
import frege.run.Kind;
import frege.run.RunTM;
import frege.runtime.Meta;
import frege.runtime.Phantom.RealWorld;
import frege.Prelude;
import frege.control.Category;
import frege.control.Semigroupoid;
import frege.java.IO;
import frege.java.Lang;
import frege.java.Util;
import frege.java.util.Regex;
import frege.prelude.Maybe;
import frege.prelude.PreludeArrays;
import frege.prelude.PreludeBase;
import frege.prelude.PreludeIO;
import frege.prelude.PreludeList;
import frege.prelude.PreludeMonad;
import frege.prelude.PreludeText;

@SuppressWarnings("unused")
@Meta.FregePackage(
  source="src\\main\\frege\\io\\github\\mchav\\FregeCode.fr", time=1480229153649L, jmajor=1,
  jminor=7,
  imps={
    "frege.Prelude", "frege.prelude.PreludeArrays", "frege.prelude.PreludeBase", "frege.prelude.PreludeIO",
    "frege.prelude.PreludeList", "frege.prelude.PreludeMonad", "frege.prelude.PreludeText", "frege.java.util.Regex"
  },
  nmss={"Prelude", "PreludeArrays", "PreludeBase", "PreludeIO", "PreludeList", "PreludeMonad", "PreludeText", "Regexp"},
  symas={}, symcs={}, symis={},
  symts={
    @Meta.SymT(
      offset=368, name=@Meta.QName(kind=0, pack="io.github.mchav.fregeandroid.FregeActivity", base="TextView"), typ=0,
      kind=15, cons={}, lnks={},
      funs={
        @Meta.SymV(
          offset=489,
          name=@Meta.QName(
            kind=2, pack="io.github.mchav.fregeandroid.FregeActivity", base="TextView", member="setText"
          ),
          stri="s(ss)", sig=3, nativ="setText", depth=2, rkind=33
        ),
        @Meta.SymV(
          offset=424,
          name=@Meta.QName(kind=2, pack="io.github.mchav.fregeandroid.FregeActivity", base="TextView", member="new"),
          stri="s(s)", sig=5, nativ="new", depth=1, rkind=33
        )
      },
      nativ="android.widget.TextView"
    ),
    @Meta.SymT(
      offset=148, name=@Meta.QName(kind=0, pack="io.github.mchav.fregeandroid.FregeActivity", base="FregeActivity"),
      typ=6, kind=15, cons={}, lnks={},
      funs={
        @Meta.SymV(
          offset=289,
          name=@Meta.QName(
            kind=2, pack="io.github.mchav.fregeandroid.FregeActivity", base="FregeActivity", member="setContentView"
          ),
          stri="s(ss)", sig=8, nativ="setContentView", depth=2, rkind=33
        ),
        @Meta.SymV(
          offset=206,
          name=@Meta.QName(
            kind=2, pack="io.github.mchav.fregeandroid.FregeActivity", base="FregeActivity",
            member="getApplicationContext"
          ),
          stri="s(s)", sig=9, nativ="getApplicationContext", depth=1, rkind=33
        )
      },
      nativ="android.app.Activity"
    ),
    @Meta.SymT(
      offset=101, name=@Meta.QName(kind=0, pack="io.github.mchav.fregeandroid.FregeActivity", base="Context"), typ=10,
      kind=15, cons={}, lnks={}, funs={}, nativ="android.content.Context"
    ),
    @Meta.SymT(
      offset=61, name=@Meta.QName(kind=0, pack="io.github.mchav.fregeandroid.FregeActivity", base="Bundle"), typ=11,
      kind=15, cons={}, lnks={}, funs={}, nativ="android.os.Bundle"
    )
  },
  symvs={
    @Meta.SymV(
      offset=539, name=@Meta.QName(pack="io.github.mchav.fregeandroid.FregeActivity", base="onCreateF"), stri="s(s)",
      sig=12, depth=1, rkind=49
    )
  },
  symls={},
  taus={
    @Meta.Tau(
      kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.fregeandroid.FregeActivity", base="TextView")}
    ),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeIO", base="Mutable")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="RealWorld")}),
    @Meta.Tau(kind=0, suba=1, subb=2), @Meta.Tau(kind=0, suba=3, subb=0),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="StringJ")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Char")}),
    @Meta.Tau(kind=0, suba=5, subb=6),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="ST")}),
    @Meta.Tau(kind=0, suba=8, subb=2),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="()")}),
    @Meta.Tau(kind=0, suba=9, subb=10),
    @Meta.Tau(
      kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.fregeandroid.FregeActivity", base="Context")}
    ),
    @Meta.Tau(kind=0, suba=3, subb=12), @Meta.Tau(kind=0, suba=9, subb=4), @Meta.Tau(kind=9),
    @Meta.Tau(
      kind=2, suba=0,
      tcon={@Meta.QName(kind=0, pack="io.github.mchav.fregeandroid.FregeActivity", base="FregeActivity")}
    ),
    @Meta.Tau(kind=0, suba=3, subb=16), @Meta.Tau(kind=0, suba=9, subb=13),
    @Meta.Tau(
      kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.fregeandroid.FregeActivity", base="Bundle")}
    )
  },
  rhos={
    @Meta.Rho(rhofun=false, rhotau=0), @Meta.Rho(rhofun=false, rhotau=4), @Meta.Rho(rhofun=false, rhotau=7),
    @Meta.Rho(rhofun=false, rhotau=11), @Meta.Rho(sigma=2, rhotau=3), @Meta.Rho(sigma=1, rhotau=4),
    @Meta.Rho(rhofun=false, rhotau=13), @Meta.Rho(rhofun=false, rhotau=14), @Meta.Rho(sigma=4, rhotau=7),
    @Meta.Rho(rhofun=false, rhotau=16), @Meta.Rho(rhofun=false, rhotau=17), @Meta.Rho(sigma=1, rhotau=3),
    @Meta.Rho(sigma=7, rhotau=11), @Meta.Rho(rhofun=false, rhotau=18), @Meta.Rho(sigma=7, rhotau=13),
    @Meta.Rho(rhofun=false, rhotau=12), @Meta.Rho(rhofun=false, rhotau=19), @Meta.Rho(sigma=7, rhotau=3)
  },
  sigmas={
    @Meta.Sigma(rho=0), @Meta.Sigma(rho=1), @Meta.Sigma(rho=2), @Meta.Sigma(rho=5), @Meta.Sigma(rho=6),
    @Meta.Sigma(rho=8), @Meta.Sigma(rho=9), @Meta.Sigma(rho=10), @Meta.Sigma(rho=12), @Meta.Sigma(rho=14),
    @Meta.Sigma(rho=15), @Meta.Sigma(rho=16), @Meta.Sigma(rho=17)
  },
  exprs={@Meta.Expr()}
)
final public class FregeActivity extends android.app.Activity  {
  

@Override
public void onCreate(android.os.Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
final frege.run7.Func.U<Object,Short> res = RunTM.<frege.run7.Func.U<Object,Short>>cast(onCreateF(this)).call();
frege.prelude.PreludeBase.TST.run(res).call();
}



final public static class TTextView  {
  final public static Func.U<RealWorld, Short> setText(final android.widget.TextView arg$1, final String/*<Character>*/ arg$2) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.setText(arg$2);
            return Thunk.lazyUnit;
          }
        };
  }
  final public static Func.U<RealWorld, android.widget.TextView> $new(final android.content.Context arg$1) {
    return new Func.U.D<RealWorld, android.widget.TextView>() {
          public Lazy<android.widget.TextView> apply(final Lazy<RealWorld> _state) {
            return Thunk.<android.widget.TextView>lazy(new android.widget.TextView(arg$1));
          }
        };
  }
}
final public static class TFregeActivity  {
  final public static Func.U<RealWorld, Short> setContentView(
    final android.app.Activity arg$1, final android.widget.TextView arg$2
  ) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.setContentView(arg$2);
            return Thunk.lazyUnit;
          }
        };
  }
  final public static Func.U<RealWorld, android.content.Context> getApplicationContext(
    final android.app.Activity arg$1
  ) {
    return new Func.U.D<RealWorld, android.content.Context>() {
          public Lazy<android.content.Context> apply(final Lazy<RealWorld> _state) {
            return Thunk.<android.content.Context>lazy(arg$1.getApplicationContext());
          }
        };
  }
}
final public static Func.U<RealWorld, Short> onCreateF(final android.app.Activity arg$1) {
  final Func.U<RealWorld, android.content.Context> v2038$7616 = TFregeActivity.getApplicationContext(
        arg$1
      );
  return new Func.U.D<RealWorld, Short>() {
        public Lazy<Short> apply(final Lazy<RealWorld> arg$7680) {
          final android.content.Context v2041$7619 = v2038$7616.apply(arg$7680).call();
          final Func.U<RealWorld, android.widget.TextView> v2038$7638 = TTextView.$new(
                v2041$7619
              );
          final android.widget.TextView v2041$7641 = v2038$7638.apply(arg$7680).call();
          final Func.U<RealWorld, Short> v4801$7663 = TTextView.setText(v2041$7641, "Hello, Android - Love, Frege");
          final short v4804$7665 = (short)v4801$7663.apply(arg$7680).call();
          final Func.U<RealWorld, Short> v4805$7666 = Thunk.<Func.U<RealWorld, Short>>shared(
                new Lazy.D<Func.U<RealWorld, Short>>() {
                  public Func.U<RealWorld, Short> call() {
                    return TFregeActivity.setContentView(arg$1, v2041$7641);
                  }
                }
              ).call();
          return Thunk.<Short>nested(
                    new Lazy.D<Lazy<Short>>() {
                      public Lazy<Short> call() {
                        return v4805$7666.apply(arg$7680);
                      }
                    }
                  );
        }
      };
}

}
